name: Devbox Hibernator 😴
on:
  schedule:
    - cron: '0 22,20,12,8 * * *'  # UTC 08, 10, 20, 22 (CEST 10, 12, 22, 00)
  workflow_dispatch:
    inputs:
      whatif:
        description: 'Apply WhatIf to the hibernation script'
        required: false
        default: false
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  hibernate-all:
    runs-on: ubuntu-22.04
    name: 'Hibernate all devboxes'
    environment: Azure
    env:
      WHAT_IF: ${{ github.event.inputs.whatif || 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Run hibernation script
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: ./scripts/hibernate-devboxes.ps1 -WhatIf:$${{ env.WHAT_IF }}